### PR TITLE
Add a screenshot of #195

### PR DESCRIPTION
**Pull request by certik**
Showing that all authors agreed to 3. and 4.

### CODE REVIEW

**Comment by certik** [comment]
@moorepants, I used the _Awesome Screenshot_ Chrome extension to capture this long screenshot.

@asmeurer would you mind reviewing this as well please?

**Comment by asmeurer** [comment]
Looks good.

**Comment by leosartaj** [comment]
+1

**Comment by certik** [comment]
Thanks @asmeurer and @leosartaj for the review.

**Pull request merged**
