### PR TITLE
Fix some typos and style

### PR DESCRIPTION
**Pull request by rouckas**
Some small corrections, fix:
- missing backslash in features.tex
- repeated "including" in introduction.tex
- sentence about 2D printing in printers.tex

### CODE REVIEW

**Comment by certik** [comment]
Thanks @rouckas. @asmeurer feel free to merge this.

**Comment by asmeurer** [comment]
Also +1

**Comment by asmeurer** [comment]
Sorry, looks like there are merge conflicts now.

**Comment by rouckas** [comment]
The conflicts should be fixed now

**Pull request merged**
