### PR TITLE
Authors metadata

### PR DESCRIPTION
**Pull request by asmeurer**
Some updates in the authors metadata, in line with https://github.com/sympy/sympy-paper/issues/205. The authors metadata in the paper has to match the metadata in the PeerJ system.

### CODE REVIEW

**Comment by scopatz** [comment]
LGTM

**Comment by asmeurer** [comment]
Three things I am not clear on (I'll just pick one for each, since I am submitting today, unless someone has some suggestions):
- Should the email be included in the affiliations? 
- Should the Los Alamos and Sandia disclaimers be included in the affiliations? 
- For authors with multiple affiliations (like Andy Terrel and Matthew Curry), is the separating of the multiple institutions with a semicolon fine? 

I couldn't find any other PeerJ articles with authors from Los Alamos or Sandia.

**Comment by asmeurer** [comment]
So:
- No other peerj article seems to include the email addresses in the footnotes. So I'm going to remove them. I guess the idea is that they are available via the PeerJ site. 
- As per https://github.com/sympy/sympy-paper/issues/205, I am removing the Los Alamos and Sandia statements from the footnotes (they will go in the funding statement, see https://github.com/sympy/sympy-paper/issues/205#issuecomment-250262556).
- I am going to leave the multiple institutions as they are.

**Comment by certik** [comment]
@asmeurer just make sure the full LANL and Sandia statements are available in the final article, one way or another.

**Comment by certik** [comment]
Otherwise this looks good.

**Comment by certik** [comment]
I am reviewing 6bb9c09.
- The `rebuttal.pdf` looks good to me. The cover letter at the beginning is fine, and I went through the points, that looks good.
- The `paper.pdf` looks very good to me. Just a minor comment:

> SymPy supports a wide array of mathematical facilities. This includes functions for assum-
> ing and deducing common mathematical facts, simplifying expressions

-> These include?

I am still reviewing.

**Comment by certik** [comment]
> SymPy a dependency
> of many external projects across a wide spectrum of domains.

-> SymPy is a dependency

**Comment by asmeurer** [comment]
Can you make a separate branch + PR with your fixes?

**Comment by certik** [comment]
> This permits users to access to the same methods

-> ... permits users to access the same methods?

**Comment by certik** [comment]
Otherwise the paper is ok.

The supplement:

> The supplementary material take

-> takes?

**Comment by certik** [comment]
Those are the things I noticed.

@asmeurer I can't create the PR right now. Plus, please check the grammar fixes that I suggested above yourself and with @scopatz, as I am not a native speaker. Then just fix it and upload it.

Otherwise +1 from me.

**Comment by scopatz** [comment]
Your suggestions @certik seem correct to me!

**Comment by asmeurer** [comment]
Figured out point 3. They should be separate footnotes (duh).

**Comment by asmeurer** [comment]
OK, I'm done here. This now matches what PeerJ generates on their site:

> Aaron Meurer​1, Christopher P Smith2, Mateusz Paprocki3, Ondřej Čertík4, Sergey B Kirpichev5, Matthew Rocklin3, AMiT Kumar6, Sergiu Ivanov7, Jason K Moore8, Sartaj Singh9, Thilina Rathnayake10, Sean Vig11, Brian E Granger12, Richard P Muller13, Francesco Bonazzi14, Harsh Gupta15, Shivam Vats15, Fredrik Johansson16, Fabian Pedregosa17, Matthew J Curry18, 19, 20, Andy R Terrel21, 22, Štěpán Roučka23, Ashutosh Saboo24, Isuru Fernando10, Sumith Kulal25, Robert Cimrman26, Anthony Scopatz1
> 1Department of Mechanical Engineering, University of South Carolina, Columbia, South Carolina, United States
> 2Polar Semiconductor, Inc., Bloomington, Minnesota, United States
> 3Continuum Analytics, Inc., Austin, Texas, United States
> 4Los Alamos National Laboratory, Los Alamos, New Mexico, United States
> 5Faculty of Physics, Moscow State University, Moscow, Russia
> 6Department of Applied Mathematics, Delhi Technological University, New Delhi, India
> 7Université Paris Est Créteil, Créteil, France
> 8Mechanical and Aerospace Engineering, University of California, Davis, Davis, California, United States
> 9Mathematical Sciences, Indian Institute of Technology (BHU), Varanasi, Uttar Pradesh, India
> 10Department of Computer Science and Engineering, University of Moratuwa, Katubedda, Moratuwa, Sri Lanka
> 11University of Illinois at Urbana-Champaign, Urbana, Illinois, United States
> 12California Polytechnic State University, San Luis Obispo, California, United States
> 13Center for Computing Research, Sandia National Laboratories, Albuquerque, New Mexico, United States
> 14Department of Theory and Bio-Systems, Max Planck Institute of Colloids and Interfaces, Potsdam, Germany
> 15Indian Institute of Technology Kharagpur, Kharagpur, West Bengal, India
> 16INRIA Bordeaux-Sud-Ouest -- LFANT project-team, Talence, France
> 17INRIA -- SIERRA project-team, Paris, France
> 18Department of Physics and Astronomy, University of New Mexico, Albuquerque, New Mexico, United States
> 19Center for Quantum Information and Control, University of New Mexico, Albuquerque, New Mexico, United States
> 20Sandia National Laboratories, Albuquerque, New Mexico, United States
> 21Fashion Metric, Inc, Austin, Texas, United States
> 22NumFOCUS, Austin, TX, United States
> 23Department of Surface and Plasma Science, Faculty of Mathematics and Physics, Charles University in Prague, Praha, Czech Republic
> 24Birla Institute of Technology and Science, Pilani, K.K. Birla Goa Campus, Sancoale, Goa, India
> 25Indian Institute of Technology Bombay, Mumbai, Maharashtra, India
> 26New Technologies -- Research Centre, University of West Bohemia, Plzeň, Czech Republic

except we have "and" before "Anthony Scopatz". That probably doesn't matter. I think they will reformat the paper and use their own metadata to format the authors, not ours, so it only matters that the information is the same.

**Comment by ashutoshsaboo** [comment]
Hi @asmeurer , I am not sure if my PeerJ address - https://peerj.com/ashutoshsaboo/ is linked to my name in the Authors database for this paper or not. Can you check for the same?

**Comment by asmeurer** [comment]
@ashutoshsaboo it seems it is not. What is the email address that should be used? I think that is how it associates accounts. The one we have in PeerJ is ashutosh.saboo96@gmail.com.

**Comment by ashutoshsaboo** [comment]
That is the one that is linked to my PeerJ account as well. Can you check as to why it is not linking to my profile? Check this image as well - (Can we link with the username, because I guess PeerJ might support that? , or through the ORCID - Mine ORCID is ORCID: 0000-0001-9354-7811 ? ) 

This is my profile image-:
screenshot from 2016-10-06 14-48-04 

This is the ORCID image (I guess ORCID is itself used for linking accounts to their PeerJ profiles, as you can see in the screenshot) -:

screenshot from 2016-10-06 14-54-42

**Comment by asmeurer** [comment]
I don't see anything that might fix it. The emails do seem to be the same. I think there mgiht be a bug in their system. All the other authors either say "Confirmed" or "Invited 108 days ago", but on yours it doesn't say either. 
screenshot 2016-10-06 00 15 10

I would suggest contacting PeerJ about this. The manuscript submission number is 11410.

**Comment by asmeurer** [comment]
This is probably related to https://github.com/sympy/sympy-paper/issues/202#issuecomment-237455086. I originally had a different email for you, but I changed it.

**Comment by ashutoshsaboo** [comment]
@asmeurer Try inviting me again on PeerJ for authorship on that paper?

**Comment by ashutoshsaboo** [comment]
@asmeurer I wrote a mail to PeerJ, let's see what they reply to it. Meanwhile, if you can try to re-invite me for the authorship on PeerJ?

**Comment by asmeurer** [comment]
PeerJ sent me an email that you accepted the invitation, and I see the preprint on your author page now.

**Comment by ashutoshsaboo** [comment]
@asmeurer Yes I accepted the invite. Thanks for the same. :+1:

**Pull request merged**
