### PR TITLE
reformat README.md

### PR DESCRIPTION
**Pull request by leosartaj**

### CODE REVIEW

**Comment by leosartaj** [comment]
ShareLatex badge shows unknown, I guess we need to again turn it on? Maybe beacause the location of repo has changed?

**Comment by asmeurer** [comment]
Why? Markdown is better than RST.

**Comment by certik** [comment]
Let's use Markdown, it's much better.

**Comment by leosartaj** [comment]
Okay. The README.md still could get some formatting.

**Comment by asmeurer** [comment]
I fixed it a bit.

**Pull request closed without merging**
