### PR TITLE
Add the overview of module categories.

### PR DESCRIPTION
**Pull request by scolobb**

### CODE REVIEW

**Comment by asmeurer** [comment]
Can you use a vector format for the image?

**Comment by asmeurer** [comment]
Can you verify that the summary of the categories module in the feature table is correct?

**Comment by scolobb** [comment]
> Can you use a vector format for the image? 

The picture was originally LaTeX-rendered to PDF, then exported to PNG.

Would you like me to try to convert it into a vector format? (Not sure about the size of the output file).  Or would you like me to provide the picture in PDF?

**Comment by scolobb** [comment]
> Can you verify that the summary of the categories module in the feature table is correct?

No issues seen, thank you!

**Comment by certik** [comment]
@scolobb, simply leave it as pdf.

**Comment by asmeurer** [comment]
Either use a PDF, or include the xy-pic code literally.

**Comment by certik** [comment]
@scolobb try to get this merged soon please. We are now in the review phase already.

**Comment by asmeurer** [comment]
The only change I want to see is png -> vector. Everything else can be fixed in review after we merge.

**Comment by scolobb** [comment]
Ah, sorry, I thought your comments started the review phase already. I should have the change ready in a couple of hours.

**Comment by scolobb** [comment]
I went with including the Xy-pic code directly, since it seems to be the simplest way (and I don't know how I hadn't thought about that before :D ).

Sorry again for the delay; I wasn't aware that my pull request was blocking the progress.

**Comment by certik** [comment]
Thanks @scolobb.

**Pull request merged**
