### PR TITLE
Features table

### PR DESCRIPTION
**Pull request by scopatz**
Added a features table with major features and descriptions.

### CODE REVIEW

**Comment by asmeurer** [comment]
It doesn't seem to be wrapping the text.

**Comment by scopatz** [comment]
There shouldn't be any lines over ~85 col, so I wouldn't expect text wrapping.

**Comment by asmeurer** [comment]
Use ~\cite.

**Comment by sumith1896** [comment]
Hi @scopatz,

The table overflows seems to overflow. Maybe there is too much in one line. We'll need proper breaks
ftab
Other than that the table seems to be out of place but that can be fixed later.
As @asmeurer said, use `\cite{}`.
The content looks fine to me for now. We can have more fine tuning of this later.

**Comment by scopatz** [comment]
Hi @Sumith1896, I think that the text wrapping should work now.  Sorry about that.

**Comment by moorepants** [comment]
Merging we can clean it up later, wrt to fitting the page.

**Comment by scopatz** [comment]
I thought I fixed the page fitting issue.

**Comment by asmeurer** [comment]
It overflows past the bottom of the page.

**Comment by scopatz** [comment]
Oh I see.

**Pull request merged**
