### PR TITLE
Add criteria for authorship that we use

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by certik** [comment]
@moorepants, @scopatz, @asmeurer let me know if you are ok with the wording.

**Comment by scopatz** [comment]
This seems fine to me @certik. Thanks for adding this.

**Comment by ashutoshsaboo** [comment]
Yeah This seems to be fine I guess! @certik :smile:

**Comment by asmeurer** [comment]
Looks good to me too.

**Comment by moorepants** [comment]
I think this is ok, but I would like us to consider adding all willing committers to SymPy as authors.

@ctb did this for there khmer package:

http://f1000research.com/articles/4-900/v1

Note the discussion from the reviewers about the author list.

What constitutes "substantial contributions"? And should we exclude all the committers from paper authorship just because they didn't contribute to the writing of the paper?

For example, @ashutoshsaboo just started helping the community a month ago and he'll be an author it seems, but we have people like Chris Smith, who has the most commits, and he won't be an author?

I'm not sure if I'm ok with that.

Are we simply putting out a call on the email list asking "would you like to be an author?" and only adding people that respond? Or do they have to respond _and_ help write the paper?

**Comment by scopatz** [comment]
> Or do they have to respond and help write the paper?

My understanding is that they have to help write the paper to be an author. Anyone else can be covered in the acknowledgements.

**Comment by certik** [comment]
Yes, my plan was to send another email to the list asking people to consider becoming authors. I just wanted to have some rules in the README that we can all agree upon. We can discuss relaxing the rules, but I think journals have rules about who can be an author, and I think our rules in the README are consistent with those. As @scopatz just commented.

I was also planning emailing the first N authors from the commit list personally. I was thinking of using N=10.

Now when we have the first draft of the paper ready as well as the workflow on github figured out, it seems like a good time to do so.

**Comment by certik** [comment]
@moorepants, I read the discussion at the link you posted. Clearly the reviewers are objecting, and our criteria in the README fix the objections:

1) Substantial contributions to the conception or design of the work; or the
acquisition, analysis, or interpretation of data for the work; AND

2) Drafting the work or revising it critically for important intellectual
content; AND

3) Final approval of the version to be published; AND

4) Agreement to be accountable for all aspects of the work in ensuring that
questions related to the accuracy or integrity of any part of the work are
appropriately investigated and resolved.

You said "willing" committers. What that means is that they must be willing to agree upon 3) and 4). They already satisfy 1), as long as their contribution to sympy is substantial.

So what we are asking them is to also satisfy 2), which is really not much to ask. And it's fair to ask to help out with the paper if they want to be authors. Note that 2) in my opinion can be satisfied with say just reviewing PRs here, or just providing feedback related to the content of the article.

**Comment by ctb** [comment]
Since I got tagged in, I'll say that there are generally no rules beyond
"what the authors decide amongst themselves." Our mistake (such as it was) in
the f1000 research paper was in explicitly stating our criterion...

Personally if it's a software paper I think it should be everyone with
github commits.

**Comment by certik** [comment]
@ctb, note that for SymPy, that's 504 authors. We don't even know their affiliations, i.e. not all will reply to their emails on time if we write them. Are you aware of any papers with 504 authors?

**Comment by moorepants** [comment]
There are a number of physics papers with huge author lists. The latest gravitational wave one is similar. I seriously doubt that all the authors on these huge physics papers actually write or review the paper.

**Comment by asmeurer** [comment]
Supposedly every author of LIGO paper [did indeed sign off on it](https://academia.stackexchange.com/questions/63440/what-is-the-point-of-listing-1000-authors-for-a-single-scientific-paper#comment152319_63458).

**Comment by moorepants** [comment]
Cool. I'm fine with the author criteria as long was we ask the top N contributors if they want to be added as authors. Ondrej can choose N.

**Comment by certik** [comment]
@moorepants I just asked the first N=30 sympy authors.

**Comment by ctb** [comment]
(Lots more discussion than on the f1000 research link, here: http://ivory.idyll.org/blog/2015-authorship-on-software-papers.html)

**Pull request merged**
