### PR TITLE
Final fixes

### PR DESCRIPTION
**Pull request by asmeurer**
Some final fixes before submission. I plan to submit off this branch.

### CODE REVIEW

**Comment by asmeurer** [comment]
So it turns out we need a "track changes" version of the pdf. I am working starting from a xonsh script from @scopatz which uses latexdiff. But there are some issues that I need to work out.

**Comment by asmeurer** [comment]
OK, someone should look over the diff files and make sure they look fine. You can build them with 

```
make diff
```

The diff script requires `xonsh`. Also `latexdiff` (which should come with your TeX installation). This will build `paper-diff.pdf` and `supplement-diff.pdf`. 

Two known issues:
- [ ] Deleted sections (from the supplement) just show up as deleting the section header, because it doesn't pull in the deleted tex files. This can likely be fixed by pulling in the files from the old git tag.
- [ ] The references for the supplement are not diffed. If you uncomment the line in `diff.xsh`, you get the build error:

```
[12 <./images/supp-fig2-integral_steps.png>]) (./comparison_with_mma-diff.tex
[13]) (./supplement-diff.bbl

! LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.29 ...tem[Brent and Zimmermann, 2010]{zimmerman}

!  ==> Fatal error occurred, no output PDF file produced!
```

**Comment by certik** [comment]
Thanks for https://github.com/sympy/sympy-paper/pull/210/commits/2b45728a869f62cd5c43251956913f5391718426, that should do it.

**Comment by certik** [comment]
Here are the current [paper-diff.pdf](https://github.com/isuruf-bot/sympy-paper/raw/16b89d3f41c3af37d362da549b4eb6c319bd3b4a/paper-diff-210.pdf) and [paper-diff-supplement.pdf](https://github.com/isuruf-bot/sympy-paper/raw/16b89d3f41c3af37d362da549b4eb6c319bd3b4a/paper-diff--supplement.pdf).

I am reviewing it now.

**Comment by certik** [comment]
@asmeurer I looked at both diffs, I think they look good. However, I though the table with "projects using sympy" was moved into the main article, but the diff doesn't seem to show it as a new thing.

The minor things you mentioned are fine I think. My understanding is that this is mainly for the editor and reviewers, so that they can check what was changed. If in doubt, they can always consult the old pdf and the new pdf.

**Comment by asmeurer** [comment]
Feel free to push any changes to this branch.

**Comment by asmeurer** [comment]
So I guess the issue I noted above works both ways. Because of the way the includes work, files that were moved to or from the supplement only show a diff for their header. Perhaps we can fix it by diffing them against empty files.

**Comment by asmeurer** [comment]
I don't plan on working on this until tomorrow. If you want to take a stab at it go ahead.

**Comment by certik** [comment]
@asmeurer I am going to bed myself. I think it's fine to leave as is, I would just put this explanation somewhere as a comment/memo when you upload. But if you feel it should be fixed, we can work on in tomorrow.

**Comment by asmeurer** [comment]
Showing blue underlines for the new files is easy enough. We just need to diff against an empty file. 

For the deleted files, it's a little harder. We also can diff against an empty file, but we also would have to add a fake "include" against the empty file in the main document. This isn't a big deal for the supplement, but for the main paper I don't want to upload an empty include file to PeerJ.

**Comment by asmeurer** [comment]
OK, the new sections basic usage and projects that depend on SymPy now show up in blue. I don't want to mess with the deleted ones. The section titles appear. I'll just leave a note to the reviewers that deleted sections only show their section titles in red. 

Now let me see if I can fix the supplement references.

**Comment by asmeurer** [comment]
Fixed the supplement bbl issue. Should be ready to go.

**Comment by asmeurer** [comment]
@certik do you want to give this one last look before I submit?

**Comment by certik** [comment]
Listing 1. on page 19 of paper-diff-210.pdf has some LaTeX garbage in it.

**Comment by certik** [comment]
Otherwise I think it looks good.

**Comment by asmeurer** [comment]
OK, fixed.

**Comment by asmeurer** [comment]
OK, it's been resubmitted! This is the text I put in the note to the staff/editor/reviewers:

> Tables 1, 2, 3 and Listing 1 are in the source file manuscript and can be found in the .tex files.
> 
> The file pprint.pdf has been used to work around issues with displaying Unicode characters in LaTeX. Its contents should appear inline with the text, not as a figure. 
> 
> Due to difficulties with the latexdiff program, in the "track changes" documents, for entire sections that have been removed, only the section titles are shown in red (for example, the "Acknowledgements" section). The removed section content is not shown. Additionally, changes to code examples are not shown.

**Comment by certik** [comment]
Thanks @asmeurer.

I checked and indeed 0c38101 fixed the issue in the diff.

**Pull request merged**
