### PR TITLE
Reviews II (everyone push to this branch)

### PR DESCRIPTION
**Pull request by asmeurer**
A continuation of https://github.com/sympy/sympy-paper/pull/144. Everyone push their changes to the `reviews` branch. Push and pull often to avoid merge conflicts. If you don't have push access, let me know and I'll give it to you.

### CODE REVIEW

**Comment by ellisonbg** [comment]
I should be able to take a pass at review tomorrow...

**Comment by asmeurer** [comment]
Great. We plan to submit on Friday.

**Comment by scolobb** [comment]
I should be able to go through the whole paper in the next 24 hours.

**Comment by scopatz** [comment]
Thanks @scolobb

**Comment by ellisonbg** [comment]
Reviewing now and will push edits immediately...

**Comment by scolobb** [comment]
I have reread the whole paper and fixed some wording and punctuation issues.  Will try to follow further commits to this branch.

**Comment by ellisonbg** [comment]
I have taken a solid pass on the paper and have pushed all my commits. Looking really good!

**Comment by certik** [comment]
Thanks @ellisonbg. I am glad you like it.

**Pull request merged**
