### PR TITLE
Citing Stats module

### PR DESCRIPTION
**Pull request by Upabjojr**

### CODE REVIEW

**Comment by asmeurer** [comment]
You can add the citation to the features table. I wouldn't add a one sentence paragraph to the supplement. If @mrocklin or you want to write more, that's fine, but if you just want some text to attach a citation to, you should use the features table.

**Comment by asmeurer** [comment]
Missing some commas in the bib file

**Comment by sumith1896** [comment]
Build should be fixed by https://github.com/sympy/sympy-paper/pull/136/commits/b0b1d0e94fc0b7203c7bf1dd604a0aa4d97706f5 
Even I feel that the citation should go to the features table.

**Comment by asmeurer** [comment]
Pushed a fix so we can get this merged. Please open a new PR if you want to write something on stats (and do so soon if you are).

**Comment by Upabjojr** [comment]
I think that the reference to the paper can be enough.

**Pull request merged**
