### PR TITLE
Update patches counts using a newer sympy commit

### PR DESCRIPTION
**Pull request by certik**
Update all relevant files.

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks @certik! I'd like to remain last author, please I am not sure if this PR changes that.

**Comment by certik** [comment]
It does change it. We'll have to create a different ordering than by the number of patches. I can do that in a future PR.

**Comment by scopatz** [comment]
Sure, or we could just manually move me to the end at the last minute :)

**Comment by certik** [comment]
@scopatz well, I don't want manual fiddling with authors when we have that many, since that's a recipe for a mistake. So I fixed it in #162.

**Pull request merged**
