### PR TITLE
Fix for #87

### PR DESCRIPTION
**Pull request by isuruf**
- Exit early if PR is from fork
- Retry git push several times

### CODE REVIEW

**Comment by certik** [comment]
Looks like it works, let's try it out.

**Comment by asmeurer** [comment]
Let's also remind everyone to push up branches to origin, not to forks. Everyone should have push access. If someone wants to contribute and doesn't they can be added.

**Comment by certik** [comment]
@asmeurer is the motivation to get the pdf pushed automatically from the PR?

**Comment by asmeurer** [comment]
Yes, @isuruf's bot won't build the PDF unless the branch is on sympy/sympy-paper. It's obviously not a requirement to have it, since Travis itself will build the PDF either way, but it's nice for the reviewers to have. 

Also, as we move into the editing stage, I think it will be easier if we push to shared branches, instead of everyone having their own branches with tons of merge conflicts among each other (but I'm still unclear on what exactly the best workflow for this will be).

**Comment by certik** [comment]
I see. Makes sense.

**Pull request merged**
