### PR TITLE
Fixed README text issue

### PR DESCRIPTION
**Pull request by ashutoshsaboo**
Please look into this. @certik @asmeurer 

Thanks. :smile:

### CODE REVIEW

**Comment by ashutoshsaboo** [comment]
Should we merge this as soon as the tests pass, because it's not related to the paper? @certik @asmeurer

**Comment by asmeurer** [comment]
Yep. I've enabled required status checks so that we don't break the build bot, but as soon as Travis runs we should merge this.

**Comment by asmeurer** [comment]
Feel free to merge it yourself (you should have merge access).

**Comment by ashutoshsaboo** [comment]
@asmeurer Yes I do have merge access. I'll merge the same as soon as the Travis passes. :+1:

**Comment by certik** [comment]
+1 to merge.

**Comment by ashutoshsaboo** [comment]
The Travis tests seem to fail. Again I guess issue with the paper upload only,I guess @isuruf ?

cc/ @asmeurer @certik

**Comment by certik** [comment]
@ashutoshsaboo I fixed it in #86.

**Pull request merged**
