### PR TITLE
First draft of polys.tex

### PR DESCRIPTION
**Pull request by mattpap**
Some horrible writing, I doubt it's worthwhile to include. Citations are needed. @certik please review.

### CODE REVIEW

**Comment by sumith1896** [comment]
Thanks @mattpap for starting this :smile: I'll have a look into this today evening.

**Comment by asmeurer** [comment]
I'm going to merge it, and review it at https://github.com/sympy/sympy-paper/pull/144. Feel free to push to that (I'll give you push access). We should probably add a citation for your master's thesis.

**Comment by certik** [comment]
Thanks a lot @mattpap! Thanks for merging @asmeurer.

**Comment by asmeurer** [comment]
@mattpap see https://github.com/sympy/sympy-paper/pull/144#issuecomment-220080426. The content here looks good. It just needs a few citations added (should be easy, since I've already imported your bib file into our bib file).

**Pull request merged**
