### PR TITLE
Add a basic .travis.yml that builds the LaTeX

### PR DESCRIPTION
**Pull request by asmeurer**
Fixes https://github.com/sympy/sympy-paper/issues/20

### CODE REVIEW

**Comment by asmeurer** [comment]
[This works](https://travis-ci.org/asmeurer/sympy-paper/builds). I guess it will take a little while for the PR Travis builds to run, since they are on the SymPy queue.

**Comment by certik** [comment]
Thanks. It doesn't work, since 5fb0b7e8b63aef534a1b9a896f10f766071af55a should have broken the build, and it didn't.

**Comment by asmeurer** [comment]
It worked on my fork. What happened?

**Comment by asmeurer** [comment]
On my fork, it checked out the [commit](https://travis-ci.org/asmeurer/sympy-paper/builds/117754588#L141), but on the PR build, it checked out [FETCH_HEAD](https://travis-ci.org/sympy/sympy-paper/builds/117754592#L149), which, you can see from the line above, is the merge commit of the PR. Since I already pushed a fixed commit by the time the build started, it tested against that, instead of the commit it was supposed to test against. I wonder how long Travis has had this bug.

**Comment by certik** [comment]
I see. I think it works, so we can merge this.

**Comment by asmeurer** [comment]
Apparently it's [intended behavior](https://github.com/travis-ci/travis-ci/issues/2430). I guess the moral is that if you want to check Travis builds against older commits you should always check the build on your fork, not the PR build.

**Comment by certik** [comment]
I am testing the new Travis build in #23, just in case.

**Pull request merged**
