### PR TITLE
Added Author Details

### PR DESCRIPTION
**Pull request by ashutoshsaboo**
Please look into this PR @scopatz @moorepants @asmeurer . 

Thanks. :smile:

### CODE REVIEW

**Comment by certik** [comment]
+1

**Comment by certik** [comment]
Closing & reopening to trigger a rebuild against the latest master.

**Comment by ashutoshsaboo** [comment]
@certik Do we merge this?

**Comment by certik** [comment]
@scopatz needs to merge this, per the README file.

@ashutoshsaboo I think you didn't run ./prettify.sh on it, did you? It revealed that you left a white space error in there....

**Comment by ashutoshsaboo** [comment]
I re-ran the prettify.sh script and re-pushed the commit. @certik 

I guess after it passes the tests, then we can go ahead merging it now @certik @scopatz .

**Comment by certik** [comment]
Thanks for fixing it @ashutoshsaboo.

@scopatz this is +1 from me to merge.

**Comment by scopatz** [comment]
Looks good to me. Thanks.

**Comment by ashutoshsaboo** [comment]
Thanks. :+1:

**Pull request merged**
