### PR TITLE
Minor quantum rewording, review of appendices

### PR DESCRIPTION
**Pull request by flacjacket**
The appendices commit is a bit messy, there are some changes that GitHub doesn't highlight correctly, if needed I can pull it apart into a few commits.

### CODE REVIEW

**Comment by certik** [comment]
Thanks @flacjacket, much appreciated. I'll let @asmeurer to review it.

**Comment by asmeurer** [comment]
Can you push future changes to the reviews branch (I've given you push access). That way we are all pushing to the same branch and avoid merge conflicts. 

I am +1 to merge this as soon as Travis finishes. You can also merge it straight into `reviews` if you want.

**Comment by flacjacket** [comment]
@asmeurer ah, sorry, I didn't look closely enough to notice the reviews branch PR, I can merge these commits in there so it doesn't kick up tons of conflict, thanks for letting me know

**Comment by asmeurer** [comment]
Yeah, master should be merged into reviews. It looks like there are already merge conflicts.

**Pull request merged**
